//! The checked-in `herdr-plugin.toml` and the module that generates it.
//!
//! Herdr reads `herdr-plugin.toml` from the default branch of the repository
//! to discover and install the plugin, and the marketplace indexes only
//! repositories whose manifest parses with its required metadata. So the file
//! has to be checked in — but a checked-in file is one a person can edit, and
//! an edit that disagrees with the binary's actual subcommands is a plugin
//! that installs cleanly and then fails on its first action.
//!
//! These tests are the join: the file is generated by
//! `hrc herdr manifest`, and CI fails if the committed bytes are not the
//! bytes that command produces.

use std::path::{Path, PathBuf};
use std::process::Command;

fn repository_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is `crates/hrc-cli`.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("the crate lives two directories below the workspace root")
        .to_path_buf()
}

fn manifest_path() -> PathBuf {
    repository_root().join("herdr-plugin.toml")
}

fn hrc() -> Command {
    Command::new(env!("CARGO_BIN_EXE_hrc"))
}

#[test]
fn the_repository_carries_a_manifest_herdr_can_discover() {
    let path = manifest_path();

    assert!(
        path.is_file(),
        "{} is missing; Herdr and the plugin marketplace both find a plugin by \
         reading this file from the default branch",
        path.display()
    );
}

#[test]
fn the_committed_manifest_is_the_one_this_build_generates() {
    let generated = hrc()
        .args(["herdr", "manifest"])
        .output()
        .expect("the manifest command should run");

    assert!(
        generated.status.success(),
        "`hrc herdr manifest` failed: {}",
        String::from_utf8_lossy(&generated.stderr)
    );

    let generated = String::from_utf8(generated.stdout).expect("the manifest is UTF-8");
    let committed = std::fs::read_to_string(manifest_path()).expect("the manifest is readable");

    // Compared with line endings normalized: the file is text that Git may
    // check out with either, and a manifest that differs only in how a
    // newline is spelled is not a manifest that drifted.
    assert_eq!(
        committed.replace("\r\n", "\n"),
        generated.replace("\r\n", "\n"),
        "herdr-plugin.toml is out of date. Regenerate it:\n\n    \
         cargo run --quiet --bin hrc -- herdr manifest > herdr-plugin.toml\n"
    );
}

#[test]
fn every_command_the_manifest_names_is_a_subcommand_this_binary_accepts() {
    // The failure this prevents: a manifest entry point that installs fine
    // and then produces a usage error the first time a person clicks it.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");
    let manifest = &manifest["manifest"];

    let commands = [
        &manifest["startup"],
        &manifest["actions"],
        &manifest["events"],
        &manifest["panes"],
    ]
    .into_iter()
    .flat_map(|entries| entries.as_array().expect("an array of entries").iter())
    .map(|entry| {
        entry["command"]
            .as_array()
            .expect("an argv array")
            .iter()
            .map(|argument| argument.as_str().expect("an argv string").to_owned())
            .collect::<Vec<_>>()
    });

    for command in commands {
        // The first element is the plugin-relative path to this same binary,
        // which the test harness knows by another name.
        let arguments = &command[1..];

        let output = hrc()
            .args(arguments)
            .arg("--help")
            .output()
            .expect("the subcommand should run");

        assert!(
            output.status.success(),
            "the manifest advertises `hrc {}`, which this binary does not accept:\n{}",
            arguments.join(" "),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn the_build_steps_are_the_same_on_every_platform() {
    // The property that replaced a pair of per-platform shell scripts, and
    // the reason it is asserted rather than assumed.
    //
    // The PowerShell half failed on the first real Windows install. `git
    // describe` writes to standard error in a checkout with no tags — the
    // ordinary case, because Herdr installs from a commit — and Windows
    // PowerShell turns a redirected native command's stderr into a
    // terminating error. `cargo build` would have failed next for the same
    // reason. Neither could be reproduced on the PowerShell available to
    // test with, because version 7 relaxed that behavior.
    //
    // Two scripts were two implementations of one idea, only one of which
    // anyone had ever run. `cargo` is the same program on all three
    // platforms, so a build step that is only `cargo` has nothing left to
    // diverge.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");

    let steps = manifest["manifest"]["build"]
        .as_array()
        .expect("an array of build steps");
    assert!(
        !steps.is_empty(),
        "the plugin needs a build step to install"
    );

    for step in steps {
        assert!(
            step.get("platforms").is_none_or(serde_json::Value::is_null),
            "a build step restricted to some platforms is a second flow: {step}"
        );

        let command: Vec<&str> = step["command"]
            .as_array()
            .expect("an argv array")
            .iter()
            .map(|argument| argument.as_str().expect("an argv string"))
            .collect();

        assert_eq!(
            command.first(),
            Some(&"cargo"),
            "a build step that runs an interpreter is a per-platform script \
             by another name: {command:?}"
        );

        // `--locked` is what makes an install build the dependency versions
        // this repository actually tested. Only the installing steps take it;
        // the cleanup step is not an install.
        if command.contains(&"install") {
            assert!(
                command.contains(&"--locked"),
                "a build step should install from the committed lockfile: {command:?}"
            );
        }
    }

    // `cargo install --path` builds into the workspace's own `target`
    // directory and leaves roughly four hundred megabytes there, inside the
    // Herdr plugins folder, for as long as the plugin is installed. Measured,
    // not assumed: 407.8 MiB on the run that produced this test.
    let cleans = steps.iter().any(|step| {
        step["command"]
            .as_array()
            .expect("an argv array")
            .iter()
            .any(|argument| argument == "clean")
    });
    assert!(
        cleans,
        "the build should reclaim its own artifacts: {steps:?}"
    );
}

#[test]
fn one_build_step_installs_where_the_manifest_looks_and_one_onto_the_path() {
    // The two copies are the install contract. The manifest invokes
    // `bin/hrc` and cannot depend on PATH; a person's terminal and the agent
    // skill's `hrc --help` discovery need `hrc` on PATH. A build that
    // produced only one of them would half-work in a way nobody notices
    // until they try the other.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");

    let commands: Vec<Vec<String>> = manifest["manifest"]["build"]
        .as_array()
        .expect("an array of build steps")
        .iter()
        .map(|step| {
            step["command"]
                .as_array()
                .expect("an argv array")
                .iter()
                .map(|argument| argument.as_str().expect("an argv string").to_owned())
                .collect()
        })
        .collect();

    // `cargo install --root .` writes to `./bin/`, which is exactly where
    // `EXECUTABLE` points, and appends `.exe` there itself on Windows.
    let into_plugin = commands
        .iter()
        .filter(|command| command.windows(2).any(|pair| pair == ["--root", "."]))
        .count();
    assert_eq!(
        into_plugin, 1,
        "exactly one step should install into the plugin root: {commands:?}"
    );

    let onto_path = commands
        .iter()
        .filter(|command| command.iter().any(|argument| argument == "install"))
        .filter(|command| !command.iter().any(|argument| argument == "--root"))
        .count();
    assert_eq!(
        onto_path, 1,
        "exactly one step should install onto the PATH: {commands:?}"
    );
}
