//! The checked-in `herdr-plugin.toml` and the module that generates it.
//!
//! Herdr reads `herdr-plugin.toml` from the default branch of the repository
//! to discover and install the plugin, and the marketplace indexes only
//! repositories whose manifest parses with its required metadata. So the file
//! has to be checked in — but a checked-in file is one a person can edit, and
//! an edit that disagrees with the binary's actual subcommands is a plugin
//! that installs cleanly and then fails on its first action.
//!
//! These tests are the join: the file is generated by
//! `hrc herdr manifest`, and CI fails if the committed bytes are not the
//! bytes that command produces.

use std::path::{Path, PathBuf};
use std::process::Command;

fn repository_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is `crates/hrc-cli`.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("the crate lives two directories below the workspace root")
        .to_path_buf()
}

fn manifest_path() -> PathBuf {
    repository_root().join("herdr-plugin.toml")
}

fn hrc() -> Command {
    Command::new(env!("CARGO_BIN_EXE_hrc"))
}

#[test]
fn the_repository_carries_a_manifest_herdr_can_discover() {
    let path = manifest_path();

    assert!(
        path.is_file(),
        "{} is missing; Herdr and the plugin marketplace both find a plugin by \
         reading this file from the default branch",
        path.display()
    );
}

#[test]
fn the_committed_manifest_is_the_one_this_build_generates() {
    let generated = hrc()
        .args(["herdr", "manifest"])
        .output()
        .expect("the manifest command should run");

    assert!(
        generated.status.success(),
        "`hrc herdr manifest` failed: {}",
        String::from_utf8_lossy(&generated.stderr)
    );

    let generated = String::from_utf8(generated.stdout).expect("the manifest is UTF-8");
    let committed = std::fs::read_to_string(manifest_path()).expect("the manifest is readable");

    // Compared with line endings normalized: the file is text that Git may
    // check out with either, and a manifest that differs only in how a
    // newline is spelled is not a manifest that drifted.
    assert_eq!(
        committed.replace("\r\n", "\n"),
        generated.replace("\r\n", "\n"),
        "herdr-plugin.toml is out of date. Regenerate it:\n\n    \
         cargo run --quiet --bin hrc -- herdr manifest > herdr-plugin.toml\n"
    );
}

#[test]
fn every_command_the_manifest_names_is_a_subcommand_this_binary_accepts() {
    // The failure this prevents: a manifest entry point that installs fine
    // and then produces a usage error the first time a person clicks it.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");
    let manifest = &manifest["manifest"];

    let commands = [
        &manifest["startup"],
        &manifest["actions"],
        &manifest["events"],
        &manifest["panes"],
    ]
    .into_iter()
    .flat_map(|entries| entries.as_array().expect("an array of entries").iter())
    .map(|entry| {
        entry["command"]
            .as_array()
            .expect("an argv array")
            .iter()
            .map(|argument| argument.as_str().expect("an argv string").to_owned())
            .collect::<Vec<_>>()
    });

    for command in commands {
        // `node` and the plugin-relative launcher path come first; the rest
        // is the `hrc herdr ...` invocation, which the test harness reaches
        // through the binary directly.
        let arguments = &command[2..];

        let output = hrc()
            .args(arguments)
            .arg("--help")
            .output()
            .expect("the subcommand should run");

        assert!(
            output.status.success(),
            "the manifest advertises `hrc {}`, which this binary does not accept:\n{}",
            arguments.join(" "),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

/// The build steps as argv arrays, read out of the generated manifest.
fn build_steps() -> Vec<(Option<Vec<String>>, Vec<String>)> {
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");

    manifest["manifest"]["build"]
        .as_array()
        .expect("an array of build steps")
        .iter()
        .map(|step| {
            let platforms = step.get("platforms").and_then(|platforms| {
                platforms.as_array().map(|platforms| {
                    platforms
                        .iter()
                        .map(|platform| platform.as_str().expect("a platform").to_owned())
                        .collect()
                })
            });
            let command = step["command"]
                .as_array()
                .expect("an argv array")
                .iter()
                .map(|argument| argument.as_str().expect("an argv string").to_owned())
                .collect();
            (platforms, command)
        })
        .collect()
}

#[test]
fn installing_the_plugin_compiles_nothing() {
    // The property that matters, and the reason it is asserted rather than
    // assumed. The build steps used to be `cargo`, and that contradicted the
    // whole point of publishing the executable to npm: the install path most
    // people take still needed a toolchain. It failed on the first real
    // Windows install with `linker `link.exe` not found` — Visual Studio
    // Build Tools, several gigabytes, to read an inbox pane.
    //
    // Making that build portable, which is what the previous version of this
    // test asserted, was solving the wrong problem.
    let steps = build_steps();
    assert!(
        !steps.is_empty(),
        "the plugin needs a build step to install"
    );

    for (_, command) in &steps {
        for compiler in ["cargo", "rustc", "rustup", "cc", "gcc", "clang", "make"] {
            assert!(
                !command.iter().any(|argument| argument == compiler),
                "a build step that compiles needs a toolchain: {command:?}"
            );
        }

        assert!(
            command.iter().any(|argument| argument == "npm"),
            "a build step should install the published executable: {command:?}"
        );
    }
}

#[test]
fn the_build_installs_exactly_the_version_the_manifest_declares() {
    // A floating `latest` would let Herdr read one version's manifest and
    // install another version's executable, so the entry points it
    // registered and the binary answering them could disagree.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");
    let version = manifest["manifest"]["version"].as_str().expect("a version");
    let pinned = format!("herdr-remote-channel@{version}");

    for (_, command) in build_steps() {
        assert!(
            command.contains(&pinned),
            "a build step should pin `{pinned}`: {command:?}"
        );
    }
}

#[test]
fn every_platform_the_plugin_claims_can_install_it() {
    // A platform the manifest lists with no step that applies to it installs
    // nothing and then fails at the first entry point, which is a worse
    // failure than refusing to install at all.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");

    let steps = build_steps();

    for platform in manifest["manifest"]["platforms"]
        .as_array()
        .expect("an array of platforms")
    {
        let platform = platform.as_str().expect("a platform");
        let applicable = steps
            .iter()
            .filter(|(platforms, _)| match platforms {
                Some(platforms) => platforms.iter().any(|entry| entry == platform),
                None => true,
            })
            .count();

        assert_eq!(
            applicable, 1,
            "`{platform}` should have exactly one step that installs the executable"
        );
    }
}

#[test]
fn the_platform_variants_differ_only_by_the_windows_process_wrapper() {
    // The steps are split by platform, which is the shape that a pair of
    // per-platform shell scripts also had — and that went badly once, so it
    // is worth pinning down why this is not the same mistake.
    //
    // Two scripts were two implementations of one idea, and only one of them
    // had ever been run. Here there is one command, and Windows prefixes it
    // with `cmd /c` because `npm` is `npm.cmd` there and a bare
    // `CreateProcess` does not find a `.cmd`. Strip the wrapper and the
    // steps must be identical, which is what makes this one implementation.
    let steps = build_steps();

    let stripped: Vec<Vec<String>> = steps
        .iter()
        .map(|(_, command)| match command.first().map(String::as_str) {
            Some("cmd") => command[2..].to_vec(),
            _ => command.clone(),
        })
        .collect();

    for command in &stripped {
        assert_eq!(
            command, &stripped[0],
            "the platform variants should be one command, not two: {stripped:?}"
        );
    }
}

#[test]
fn the_entry_points_run_what_the_build_step_installed() {
    // The build writes `node_modules`; the entry points launch out of it. If
    // these two ever named different paths the plugin would install
    // successfully and then fail at its first pane.
    let manifest = hrc()
        .args(["herdr", "manifest", "--json"])
        .output()
        .expect("the manifest command should run");
    let manifest: serde_json::Value =
        serde_json::from_slice(&manifest.stdout).expect("stdout should be JSON");

    for section in ["startup", "actions", "events", "panes"] {
        for entry in manifest["manifest"][section]
            .as_array()
            .expect("an array of entries")
        {
            let command: Vec<&str> = entry["command"]
                .as_array()
                .expect("an argv array")
                .iter()
                .map(|argument| argument.as_str().expect("an argv string"))
                .collect();

            // `node` rather than `node_modules/.bin/hrc`: that shim is
            // `hrc.cmd` on Windows and a bare `CreateProcess` does not find
            // a `.cmd`, while `node` is `node.exe` and resolves whichever
            // way the host spawns a command.
            assert_eq!(
                command.first(),
                Some(&"node"),
                "an entry point should run through node: {command:?}"
            );
            assert!(
                command
                    .get(1)
                    .is_some_and(|path| path.starts_with("node_modules/")),
                "an entry point should launch what the build installed: {command:?}"
            );
            assert!(
                !command[1].starts_with('/'),
                "an entry point path must be relative to the plugin root: {command:?}"
            );
        }
    }
}
